import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Aurora from "../components/Aurora";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className="min-h-screen antialiased absolute top-0 left-0 w-full h-full pointer-events-none
        z-[-1] mx-auto inset-0
        "
        >
          {" "}
          <Aurora
            colorStops={["#7cff67", "#b19eef", "#5227ff"]}
            blend={0.3}
            amplitude={1.0}
            speed={0.2}
          />
        </div>

        {children}
      </body>
    </html>
  );
}
